version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "batch-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-95c7rhkbyz6f"
s3_prefix = "batch-service"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
