AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  snabba-cash

  Sample SAM Template for snabba-cash

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  GenPresignLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: genPresign/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          S3_BUCKET: !Ref IngestBucket
      Events:
        API:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getpresign/{images}
            Method: get
      Policies:
        - Statement:
            - Sid: GenPresignPermission
              Effect: Allow
              Action:
                - s3:*
              Resource: !Sub "arn:aws:s3:::${IngestBucket}/*"

  ProcessImgLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: processImg/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      MemorySize: 2048
      Environment:
        Variables:
          S3_BUCKET_RESULT: !Ref ResultBucket
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: 
              Ref: IngestBucket     # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*
      Policies:
        - Statement:
            - Sid: PostVideoPermission
              Effect: Allow
              Action:
                - s3:*
              Resource: "*"

  GetVideoLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: getVideo/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Environment:
        Variables:
          S3_BUCKET: !Ref ResultBucket
      Events:
        API:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getvideo/{video}
            Method: get
      Policies:
        - Statement:
            - Sid: GenPresignPermission
              Effect: Allow
              Action:
                - s3:*
              Resource: "*"

  IngestBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1

  ResultBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  API:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GenPresignLambda:
    Description: "GenPresignLambda Function ARN"
    Value: !GetAtt GenPresignLambda.Arn
  GetVideoLambda:
    Description: "GetVideoLambda Function ARN"
    Value: !GetAtt GetVideoLambda.Arn
  ProcessImgLambda:
    Description: "ProcessImgLambda Function ARN"
    Value: !GetAtt ProcessImgLambda.Arn
